name: Docker test

on:
  push:
    branches:
      - master

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Build and deploy Docker image
      run: |
        docker build -t test-image ./app
        docker run -d --name test-container -p 5000:5000 test-image

    - name: Test by requesting data from imager
      run: |
        docker ps
        curl http://localhost:5000
              
    - name: Test if image has not root access inside
      run: |
        docker exec test-container id 